# Example Site settings

#google_analytics: UA-NNNNNNNN-N

remote_theme: b2a3e8/jekyll-theme-console

header_pages:
 - index.md

footer: 'follow me on <a href="https://twitter.com/sridge">twitter</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
