# Example Site settings

#google_analytics: UA-NNNNNNNN-N

remote_theme: b2a3e8/jekyll-theme-console

header_pages:
 - index.md
 - about.md
 - projects.md
 - publications.md

footer: 'follow me on <a href="https://twitter.com/sean_ridge">twitter</a> and <a href="https://github.com/sridge">GitHub</a>

style: light # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
